const questions = [
    {
      id: 1,
      topic: 'Math',
      question: 'What is pi (3.14159265) to the power of pi?',
      options: ['36.4621596072', '30.9591444', '27.1234567','9.8596'],
      correct: [0],
    },
    {
        id: 2,
        topic: 'Math',
        question: 'What is the square root of pi?',
        options: ['1.46803087', '1.80003919', '1.77245385','1.90932839'],
        correct: [2],
      },
      {
        id: 3,
        topic: 'Math',
        question: 'What is the result of 5 + 7?',
        options: ['10', '12', '15'],
        correct: [1],
      },
      {
        id: 4,
        topic: 'Math',
        question: 'Solve for x: 3x - 8 = 10',
        options: ['-1', '2', '6'],
        correct: [2],
      },
      {
        id: 5,
        topic: 'Math',
        question: 'Which of the following is a prime number?',
    options: ['12', '17', '22'],
    correct: [1],
      },
      {
        id: 6,
        topic: 'Math',
        question: 'What is the square root of 81?',
        options: ['8', '9', '10'],
        correct: [1]
      },
      {
        id: 7,
        topic: 'Math',
        question: 'If a triangle has angles 45°, 45°, and 90°, what type of triangle is it?',
    options: ['Equilateral', 'Isosceles', 'Right-angled'],
    correct: [2, 3],
      },
      {
        id: 8,
        topic: 'Math',
        question: 'What is the value of π (pi) to two decimal places?',
        options: ['3.14', '3.25', '3.50'],
        correct: [1],
      },
      {
        id: 9,
        topic: 'Math',
        question: 'If a rectangle has sides of length 8 cm and 12 cm, what is its area?',
        options: ['48 cm²', '64 cm²', '96 cm²'],
        correct: [1],
      },
      {
        id: 10,
        topic: 'Math',
        question: 'Simplify: 2/3 + 4/5',
        options: ['6/8', '22/15', '1 1/15'],
        correct: [1],
      },
      {
        id: 11,
        topic: 'History,',
        question: 'Who was the first President of the United States?',
    options: ['George Washington', 'Thomas Jefferson', 'John Adams'],
    correct: [0],
      },
      {
        id: 12,
        topic: 'History,',
        question: 'In which year did World War II begin?',
        options: ['1939', '1941', '1945'],
        correct: [0],
      },
      {
        id: 13,
        topic: 'History,',
        question: 'Which ancient civilization built the pyramids in Egypt?',
    options: ['Greek', 'Roman', 'Egyptian'],
    correct: [2],
      },
      {
        id: 14,
        topic: 'History,',
        question: 'Who was the leader of the Soviet Union during the Cuban Missile Crisis?',
    options: ['Vladimir Putin', 'Joseph Stalin', 'Nikita Khrushchev'],
    correct: [2],
      },
      {
        id: 15,
        topic: 'History,',
        question: 'What was the main cause of the French Revolution?',
    options: ['Economic inequality', 'Religious conflicts', 'Foreign invasions'],
    correct: [0],
      },
      {
        id: 16,
        topic: 'History,',
        question: 'Which explorer is credited with discovering the sea route to India?',
    options: ['Christopher Columbus', 'Vasco da Gama', 'Ferdinand Magellan'],
    correct: [1],
      },
      {
        id: 17,
        topic: 'History,',
        question: 'In which year did the Berlin Wall fall, leading to the reunification of Germany?',
    options: ['1985', '1989', '1991'],
    correct: [1],
      },
      {
        id: 18,
        topic: 'History,',
        question: 'Who was the first woman to win a Nobel Prize?',
        options: ['Marie Curie', 'Rosalind Franklin', 'Ada Lovelace'],
        correct: [0],
      },
      {
        id: 19,
        topic: 'History,',
        question: 'Which civilization is known for creating the Great Wall of China?',
    options: ['Mongol', 'Han', 'Qin'],
    correct: [2],
      },
      {
        id: 20,
        topic: 'History,',
        question: 'Who was the President of the United States during the Civil War?',
    options: ['Abraham Lincoln', 'Andrew Johnson', 'Ulysses S. Grant'],
    correct: [0],
      },
      {
        id: 21,
        topic: 'Science,',
        question: 'What are the primary colors of light?',
    options: ['Red', 'Green', 'Blue', 'Yellow'],
    correct: [0, 1, 2],
      },
      {
        id: 22,
        topic: 'Science,',
        question: 'Which elements make up the majority of Earth\'s atmosphere?',
        options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Argon'],
        correct: [0, 1],
      },
      {
        id: 23,
        topic: 'Science,',
        question: 'What is the largest planet in our solar system?',
    options: ['Mars', 'Jupiter', 'Saturn', 'Venus'],
    correct: [1],
      },
      {
        id: 24,
        topic: 'Science,',
        question: 'Which process converts sugar into energy in a cell?',
    options: ['Photosynthesis', 'Cellular Respiration', 'Mitosis', 'Fermentation'],
    correct: [1],
      },
      {
        id: 25,
        topic: 'Science,',
        question: 'What is the chemical formula for methane?',
    options: ['CH4', 'CO2', 'H2O', 'O2'],
    correct: [0],
      },
      {
        id: 26,
        topic: 'Science,',
        question: 'Which gas is responsible for the greenhouse effect?',
    options: ['Ozone', 'Carbon Dioxide', 'Methane', 'Nitrous Oxide'],
    correct: [1, 2, 3],
      },
      {
        id: 27,
        topic: 'Science,',
        question: 'What is the smallest particle of an element that retains its properties?',
    options: ['Molecule', 'Atom', 'Proton', 'Neutron'],
    correct: [1],
      },
      {
        id: 28,
        topic: 'Science,',
        question: 'Which planet is known as the "Morning Star" or "Evening Star"?',
    options: ['Mars', 'Venus', 'Mercury', 'Jupiter'],
    correct: [2],
      },
      {
        id: 29,
        topic: 'Science,',
        question: 'What is the process by which plants make their own food?',
    options: ['Respiration', 'Transpiration', 'Photosynthesis', 'Germination'],
    correct: [2],
      },
      {
        id: 30,
        topic: 'Science,',
        question: 'Which scientist developed the theory of evolution by natural selection?',
    options: ['Charles Darwin', 'Gregor Mendel', 'Louis Pasteur', 'Isaac Newton'],
    correct: [0],
      },
    {
        id: 31,
        topic: 'computer Science',
        question: 'What is the purpose of the "if" statement in programming?',
    options: ['To declare a variable', 'To perform a loop', 'To make a decision', 'To define a function'],
    correct: [2],
      },
      {
        id: 32,
        topic: 'computer Science',
        question: 'Which programming language is known for its use in web development and building dynamic websites?',
    options: ['Java', 'Python', 'JavaScript', 'C++'],
    correct: [2],
      },
      {
        id: 33,
        topic: 'computer Science',
        question: 'What is the purpose of the "if" statement in programming?',
    options: ['To declare a variable', 'To perform a loop', 'To make a decision', 'To define a function'],
    correct: [2, 3],
      },
      {
        id: 34,
        topic: 'computer Science',
        question: 'Which programming language is known for its use in web development and building dynamic websites?',
    options: ['Java', 'Python', 'JavaScript', 'C++'],
    correct: [2, 3],
      },
      {
        id: 35,
        topic: 'computer Science',
        question: 'What does HTML stand for in web development?',
        options: ['HyperText Markup Language', 'High-Level Textual Language', 'Hyper Transfer Markup Language', 'HyperLink and Text Markup Language'],
        correct: [0],
      },
      {
        id: 36,
        topic: 'computer Science',
        question: 'Which of the following is an object-oriented programming language?',
    options: ['C', 'Java', 'Assembly', 'Fortran'],
    correct: [1],
      },
      {
        id: 37,
        topic: 'computer Science',
        question: 'What is the purpose of SQL in database management?',
        options: ['To create web pages', 'To query and manipulate databases', 'To design user interfaces', 'To write server-side scripts'],
        correct: [1],
      },
      {
        id: 38,
        topic: 'computer Science',
        question: 'Which data structure follows the Last In, First Out (LIFO) principle?',
    options: ['Queue', 'Stack', 'Linked List', 'Tree'],
    correct: [1],
      },
      {
        id: 39,
        topic: 'computer Science',
        question: 'What is the role of a compiler in programming?',
    options: ['To execute code', 'To convert source code to machine code', 'To debug code', 'To design user interfaces'],
    correct: [1],
      },
      {
        id: 40,
        topic: 'computer Science',
        question: 'Which of the following is a front-end framework for building user interfaces?',
    options: ['Angular', 'Django', 'Express', 'Flask'],
    correct: [0],
      },

    {
      id: 41,
      topic: 'Programming',
      question: 'What is the purpose of the "for" loop in programming?',
    options: ['To declare a function', 'To perform a conditional check', 'To iterate over a sequence of values', 'To define a variable'],
    correct: [2],
    },
    {
        id: 42,
        topic: 'Programming',
        question: 'Which programming language is often used for scientific computing and data analysis?',
    options: ['Java', 'Python', 'C++', 'Ruby'],
    correct: [1],
      },
      {
        id: 43,
        topic: 'Programming',
        question: 'What does CSS stand for in web development?',
    options: ['Cascading Style Sheet', 'Computer Style Sheet', 'Creative Style Sheet', 'Colorful Style Sheet'],
    correct: [0],
      },
      {
        id: 44,
        topic: 'Programming',
        question: 'Which of the following are programming languages?',
        options: ['HTML', 'CSS', 'JavaScript', 'Photoshop'],
        correct: [2],
      },
      {
        id: 45,
        topic: 'Programming',
        question: 'Which of the following is a procedural programming language?',
    options: ['Python', 'JavaScript', 'C', 'Swift'],
    correct: [2],
      },
      {
        id: 46,
        topic: 'Programming',
        question: 'What is the purpose of the "try...catch" block in programming?',
    options: ['To declare variables', 'To handle exceptions', 'To define functions', 'To perform arithmetic operations'],
    correct: [1],
      },
      {
        id: 47,
        topic: 'Programming',
        question: 'Which data structure follows the First In, First Out (FIFO) principle?',
    options: ['Queue', 'Stack', 'Linked List', 'Tree'],
    correct: [0],
      },
      {
        id: 48,
        topic: 'Programming',
        question: 'What is the role of an interpreter in programming?',
    options: ['To execute code', 'To convert source code to machine code', 'To debug code', 'To design user interfaces'],
    correct: [0],
      },
      {
        id: 49,
        topic: 'Programming',
        question: 'Which of the following is a back-end framework for building web applications?',
    options: ['React', 'Angular', 'Express', 'Vue'],
    correct: [2],
      },
      {
        id: 50,
        topic: 'Programming',
        question: 'What is the purpose of the "npm" command in JavaScript development?',
    options: ['To install packages', 'To create databases', 'To track changes in source code', 'To generate documentation'],
    correct: [0],
      },
  ];
  
  export default questions;
  